### ISSUE TITLE
Upload.py

### ISSUE THREAD

**Issue by BenSpex** [SpexAI/BaMApp-Base-Model-for-Agricultural-Applications#1]
We need to create a Python script, `upload.py`, that will serve as our primary data uploading and preprocessing utility. This script should perform a series of tasks, including data transformation, folder crawling, embedding vector creation using the DinoV2 trained ViTg14 model, uploading images to DeepLake, and tracking everything in WandB.

## Tasks

Please check off these tasks as they are completed:

- [x] **Data Transformation:** Transform all input images to a standard size of 1024x1024 pixels.

- [x] **Folder Crawler:** Implement a folder crawler that searches for `.png` and `.jpg` image files in a specified directory and its subdirectories.

- [x] **Embedding Vector Creation:** Use the DinoV2 trained ViTg14 model to create an embedding vector for each image.

- [x] **DeepLake Upload:** Upload the processed images and their corresponding embedding vectors to DeepLake.

- [ ] **WandB Integration:** Integrate with WandB to track all operations, including data transformations and uploads.

- [x] **Error proofing** Add more try catch, and assert etc. to make it "fool proof"

**Comment by BenSpex** [comment]
@EtienneDavid and @geezacoleman can you please go and try it on your PC and see if you see the need to perform any changes? 
Right now I think it is running on CPU only, but it is still okay fast here

**Comment by BenSpex** [comment]
WandB, does not make sense at this stage, we will integrate it during training. We want to keep the upload phase as light as possible..
